server:
  # 应用服务 WEB 访问端口
  port: 58080

spring:
  application:
    name: RedisDemo

  # 数据源信息
  datasource:
    url: jdbc:mysql://localhost:3306/redis_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # redis信息
  redis:
    # 数据库索引，默认为0
#    database: 0
    # Redis服务器地址
    host: 192.168.31.168
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password:
    # 连接超时时间（毫秒）
    timeout: 1200
    # 使用lettuce连接redis服务端
    lettuce:
      pool:
      # 连接池最大连接数，默认8，负数表示没有限制
        max-active: 8
      # 连接池最大阻塞等待时间，默认-1，负数表示没有限制
        max-wait: -1
      # 连接池中的最大空闲连接，默认8
        max-idle: 8
      # 连接池中的最小空闲连接，默认0
        min-idle: 0

mybatis:
  mapper-locations: classpath:mappers/*.xml
